/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.insumos;

import clase.ListadoInsumos;
import control.InsumoDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo
 */
public class modificarItemInsumo extends javax.swing.JFrame {

    /**
     * Creates new form modificarItemInsumo
     */
    public modificarItemInsumo() {
        this.setTitle("Ventana Gestion Modificar Item Insumo");
        initComponents();
        vista.insumos.modificarItemInsumo.txt_idListadoCotizacion.setVisible(false);
    }

    public void actualizarTotalCampoyBD(int idInsumo) {
        InsumoDao insumox = new InsumoDao();
        if (insumox.validarQueExistaInsumo(idInsumo)) {
            //Existe entonces rescato
            //REscato el total final de la lista
            long subTotal = insumox.devolverValorTotalListadoInsumo(idInsumo);

            //Necesito actualizar la tabla y el texto con ese total
            if (insumox.modificarSubTotalInsumo(subTotal, idInsumo)) {
                JOptionPane.showMessageDialog(null, "Total Actualizado Correctamente");
                //Modificar Campo TOTAL
                vista.insumos.menuInsumo.txt_totalInsumos.setText(this.cambiarFormatoMil(String.valueOf(subTotal)));
            }
            System.out.println("VALOR TOTAL: " + subTotal);
        }
    }
        
    
    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) vista.insumos.menuInsumo.tablaInsumos.getModel();
        int a = vista.insumos.menuInsumo.tablaInsumos.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void cargarTablaInicio() {
        try {
            InsumoDao insumox = new InsumoDao();

            DefaultTableModel modelo = (DefaultTableModel) vista.insumos.menuInsumo.tablaInsumos.getModel();
            int idInsumo = Integer.parseInt(vista.insumos.menuInsumo.txt_idInsumos.getText());
            ArrayList<ListadoInsumos> listado = insumox.listadoItemsInsumo(idInsumo);

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdListadoInsumos();
                fila[1] = listado.get(i).getNombreProducto();
                fila[2] = listado.get(i).getFechaCreacion();
                fila[3] = listado.get(i).getCantidad();
                fila[4] = listado.get(i).getPrecioUnitario();
                fila[5] = listado.get(i).getSubTotal();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }
    
    
    public String cambiarFormatoMil(String valor) {
        String valorConSeparador = "";
        char[] arregloPaso = valor.toCharArray();
        int contadorPaso = 1;
        for (int i = arregloPaso.length - 1; i >= 0; i--) {
            if (contadorPaso == 3) {
                if (i == 0) {
                    valorConSeparador = valorConSeparador + arregloPaso[i];
                    contadorPaso = 1;
                } else {
                    valorConSeparador = valorConSeparador + arregloPaso[i] + ".";
                    contadorPaso = 1;
                }

            } else {
                valorConSeparador = valorConSeparador + arregloPaso[i];
                contadorPaso = contadorPaso + 1;
            }
            //System.out.println("LETRA: " + arregloPaso[i]);
        }

        StringBuilder stringPaso = new StringBuilder(valorConSeparador);
        valorConSeparador = stringPaso.reverse().toString();

        return valorConSeparador;
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_idInsumo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_codigoProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        txt_precioUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_subTotal = new javax.swing.JTextField();
        btnModificarITEM = new javax.swing.JButton();
        txt_idListadoCotizacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID INSUMO:");

        txt_idInsumo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idInsumo.setText("00000");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("FECHA:");

        txt_fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_fecha.setText("00-00-0000");

        jButton1.setText("?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Codigo Producto:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cantidad:");

        txt_cantidad.setText("0");
        txt_cantidad.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cantidadCaretUpdate(evt);
            }
        });

        txt_precioUnitario.setText("0");
        txt_precioUnitario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_precioUnitarioCaretUpdate(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Precio Unitario:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Sub Total:");

        txt_subTotal.setText("0");

        btnModificarITEM.setText("MODIFICAR");
        btnModificarITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarITEMActionPerformed(evt);
            }
        });

        txt_idListadoCotizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idListadoCotizacion.setText("00000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_idInsumo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(txt_fecha)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txt_codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1))
                                .addComponent(txt_precioUnitario)
                                .addComponent(txt_cantidad)
                                .addComponent(txt_subTotal)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_idListadoCotizacion)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_idInsumo)
                    .addComponent(txt_fecha)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_idListadoCotizacion)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_precioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(42, 42, 42)
                .addComponent(btnModificarITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        vista.insumos.menuConsultarProductoModificar menu = new vista.insumos.menuConsultarProductoModificar();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_cantidadCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cantidadCaretUpdate
        try {
            int cantidad = 0;
            if (!this.txt_cantidad.getText().isEmpty()) {
                cantidad = Integer.parseInt(this.txt_cantidad.getText().replace(".", ""));
            }

            long precioUnitario = 0;
            if (!this.txt_precioUnitario.getText().isEmpty()) {
                precioUnitario = Long.parseLong(this.txt_precioUnitario.getText().replace(".", ""));
            }

            long subTotal = cantidad * precioUnitario;

            this.txt_subTotal.setText(this.cambiarFormatoMil(String.valueOf(subTotal)));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txt_cantidadCaretUpdate

    private void txt_precioUnitarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_precioUnitarioCaretUpdate
        try {
            int cantidad = 0;
            if (!this.txt_cantidad.getText().isEmpty()) {
                cantidad = Integer.parseInt(this.txt_cantidad.getText().replace(".", ""));
            }

            long precioUnitario = 0;
            if (!this.txt_precioUnitario.getText().isEmpty()) {
                precioUnitario = Long.parseLong(this.txt_precioUnitario.getText().replace(".", ""));
            }

            long subTotal = cantidad * precioUnitario;

            this.txt_subTotal.setText(this.cambiarFormatoMil(String.valueOf(subTotal)));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txt_precioUnitarioCaretUpdate

    private void btnModificarITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarITEMActionPerformed
        try {
            if (vista.insumos.modificarItemInsumo.txt_codigoProducto.getText().isEmpty()) {
                throw new Exception("Ingrese codigo de Producto");
            }
            int cantidad = 0;
            if (!this.txt_cantidad.getText().isEmpty()) {
                cantidad = Integer.parseInt(this.txt_cantidad.getText().replace(".", ""));
            }

            long precioUnitario = 0;
            if (!this.txt_precioUnitario.getText().isEmpty()) {
                precioUnitario = Long.parseLong(this.txt_precioUnitario.getText().replace(".", ""));
            }

            long subTotal = cantidad * precioUnitario;
            int idInsumo = Integer.parseInt(vista.insumos.modificarItemInsumo.txt_idInsumo.getText());
            int codigoProducto = Integer.parseInt(vista.insumos.modificarItemInsumo.txt_codigoProducto.getText());
            int idListado = Integer.parseInt(vista.insumos.modificarItemInsumo.txt_idListadoCotizacion.getText());
            String fechaCreacion = this.txt_fecha.getText();
            //Agregar ITEM
            InsumoDao insumox = new InsumoDao();
            if (insumox.modificarItemListadoInsumo(cantidad, precioUnitario, subTotal, codigoProducto, idListado)) {
                JOptionPane.showMessageDialog(null, "Modificado Correctamente");
                //CARGAR TABLA
                this.eliminarContenidoTabla();
                this.cargarTablaInicio();
                this.actualizarTotalCampoyBD(idInsumo);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo modificar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarITEMActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(modificarItemInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(modificarItemInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(modificarItemInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(modificarItemInsumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new modificarItemInsumo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificarITEM;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JTextField txt_cantidad;
    public static javax.swing.JTextField txt_codigoProducto;
    public static javax.swing.JLabel txt_fecha;
    public static javax.swing.JLabel txt_idInsumo;
    public static javax.swing.JLabel txt_idListadoCotizacion;
    public static javax.swing.JTextField txt_precioUnitario;
    public static javax.swing.JTextField txt_subTotal;
    // End of variables declaration//GEN-END:variables
}
