/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proveedores;

import clase.Proveedor;
import control.ProveedorDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo
 */
public class menuConsultaRUTProveedor extends javax.swing.JFrame {

    /**
     * Creates new form menuConsultaRUT
     */
    public menuConsultaRUTProveedor() {
        this.setTitle("Ventana - Consultar Rut Proveedor Existentes");
        initComponents();
        this.llenarComboBoxGiroProveedores();
        

    }

    public void llenarComboBoxGiroProveedores() {
        try {
            ProveedorDao provedor = new ProveedorDao();
            ArrayList<String> listado = provedor.cargarComboBoxGiroProveedor();

            this.cbo_giro.removeAllItems();

            for (int i = -1; i < listado.size(); i++) {
                if (i == -1) {
                    this.cbo_giro.addItem("Seleccionar");
                } else {
                    this.cbo_giro.addItem(listado.get(i));
                }
            }
            /*Fin llenado*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema CBO: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_proveedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbo_giro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "RUT", "Nombre Empresa", "Giro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_proveedor.getTableHeader().setReorderingAllowed(false);
        tabla_proveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_proveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_proveedor);

        jLabel1.setText("Filtro por Giro:");

        cbo_giro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_giro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbo_giroItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(cbo_giro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) this.tabla_proveedor.getModel();
        int a = this.tabla_proveedor.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void cargarTablaInicio() {
        try {
            ProveedorDao proveedorx = new ProveedorDao();

            DefaultTableModel modelo = (DefaultTableModel) this.tabla_proveedor.getModel();
            ArrayList<Proveedor> listaProveedores = proveedorx.cargarListadoProveedores();

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listaProveedores.size(); i++) {
                fila[0] = listaProveedores.get(i).getRut();
                fila[1] = listaProveedores.get(i).getNombreEmpresa();
                fila[2] = listaProveedores.get(i).getGiro();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    public void cargarTablaListadoPorFiltro(String giro) {
        //Listar empresa
        try {
            //Vaciar Campos de la tabla
            eliminarContenidoTabla();

            ProveedorDao proveedorx = new ProveedorDao();

            DefaultTableModel modelo = (DefaultTableModel) this.tabla_proveedor.getModel();
            ArrayList<Proveedor> listaProveedores = proveedorx.rescatarConsultaProveedores(giro);

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listaProveedores.size(); i++) {
                fila[0] = listaProveedores.get(i).getRut();
                fila[1] = listaProveedores.get(i).getNombreEmpresa();
                fila[2] = listaProveedores.get(i).getGiro();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }


    private void cbo_giroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbo_giroItemStateChanged
        /*Rescatar selecccionado y listar tabla*/
        try {
            if (this.cbo_giro.getSelectedItem().equals("Seleccionar")) {
                this.eliminarContenidoTabla();
                this.cargarTablaInicio();
            } else {
                this.cargarTablaListadoPorFiltro(this.cbo_giro.getSelectedItem().toString());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_cbo_giroItemStateChanged

    private void tabla_proveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_proveedorMouseClicked
        if (evt.getClickCount() == 2) {
            //Rescatar valores y pasar
            String rut = this.tabla_proveedor.getValueAt(this.tabla_proveedor.getSelectedRow(), 0).toString();
            vista.proveedores.menuProveedores.txt_rutEmpresa.setText(rut);
            this.dispose();
        }
    }//GEN-LAST:event_tabla_proveedorMouseClicked

////    /**
////     * @param args the command line arguments
////     */
////    public static void main(String args[]) {
////        /* Set the Nimbus look and feel */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
////        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
////         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
////         */
////        try {
////            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
////                if ("Nimbus".equals(info.getName())) {
////                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
////                    break;
////                }
////            }
////        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLogger(menuConsultaRUTProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (InstantiationException ex) {
////            java.util.logging.Logger.getLogger(menuConsultaRUTProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (IllegalAccessException ex) {
////            java.util.logging.Logger.getLogger(menuConsultaRUTProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
////            java.util.logging.Logger.getLogger(menuConsultaRUTProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
////        }
////        //</editor-fold>
////        //</editor-fold>
////
////        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new menuConsultaRUTProveedor().setVisible(true);
////            }
////        });
////    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbo_giro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_proveedor;
    // End of variables declaration//GEN-END:variables
}
