/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.proveedores;

import clase.Proveedor;
import control.PedidoDao;
import control.ProveedorDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfredo
 */
public class menuProveedores extends javax.swing.JFrame {

    /**
     * Creates new form menuProveedores
     */
    public menuProveedores() {
        this.setTitle("Menu - Gestion Proveedores");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_nombreEmpresa = new javax.swing.JTextField();
        txt_giro = new javax.swing.JTextField();
        txt_rutEmpresa = new javax.swing.JTextField();
        txt_paginaWeb = new javax.swing.JTextField();
        txt_nombreContacto = new javax.swing.JTextField();
        txt_numeroContacto = new javax.swing.JTextField();
        txt_correoContacto = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btn_eliminar = new javax.swing.JButton();
        txt_ayuda = new javax.swing.JLabel();
        btn_consultaProveedores = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_nombreBanco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_nroCuentaCorriente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("RUT EMPRESA:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Nombre empresa:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Giro:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefono:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nombre:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Página WEB:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Correo");

        txt_nombreEmpresa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_nombreEmpresaCaretUpdate(evt);
            }
        });

        txt_rutEmpresa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_rutEmpresaCaretUpdate(evt);
            }
        });
        txt_rutEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rutEmpresaActionPerformed(evt);
            }
        });

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_limpiar.setText("Limpiar Campos");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Datos Contacto");

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        txt_ayuda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_ayuda.setText("?");
        txt_ayuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_ayudaMouseClicked(evt);
            }
        });

        btn_consultaProveedores.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_consultaProveedores.setText("?");
        btn_consultaProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultaProveedoresActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Datos Transferencia");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Banco:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Nro. Cuenta Corriente:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(txt_nombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(12, 12, 12)
                .addComponent(txt_numeroContacto)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_correoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ayuda)
                .addGap(9, 9, 9))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2))
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txt_nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_paginaWeb)
                                    .addComponent(txt_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(txt_rutEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_consultaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)
                        .addComponent(txt_nombreBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nroCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(367, 367, 367))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_giro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txt_rutEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultaProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_paginaWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_nombreContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_numeroContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_correoContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txt_ayuda))
                .addGap(33, 33, 33)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_nroCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rutEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rutEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rutEmpresaActionPerformed

    private void txt_ayudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_ayudaMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Formato Correo\n correo@hotmail.com\n correo@gmail.com \n correo@empresa.cl");


    }//GEN-LAST:event_txt_ayudaMouseClicked

    public void comprobarSiVieneVacio(String dato, String campo) throws Exception {
        if (dato.trim().length() <= 0) {
            throw new Exception("El campo " + campo + " no puede venir en blanco.");
        }
    }

    public void limpiarCampos() {
        this.txt_ayuda.setText("");
        this.txt_correoContacto.setText("");
        this.txt_giro.setText("");
        this.txt_nombreContacto.setText("");
        this.txt_nombreEmpresa.setText("");
        this.txt_numeroContacto.setText("");
        this.txt_paginaWeb.setText("");
        this.txt_rutEmpresa.setText("");
        this.txt_nombreBanco.setText("");
        this.txt_nroCuentaCorriente.setText("");
    }


    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        try {
            this.comprobarSiVieneVacio(this.txt_nombreEmpresa.getText(), "NOMBRE EMPRESA");
            this.comprobarSiVieneVacio(this.txt_giro.getText(), "GIRO");
            this.comprobarSiVieneVacio(this.txt_rutEmpresa.getText(), "RUT EMPRESA");
            //this.comprobarSiVieneVacio(this.txt_paginaWeb.getText(), "PAGINA WEB");
            //this.comprobarSiVieneVacio(this.txt_nombreContacto.getText(), "NOMBRE CONTACTO");
            //this.comprobarSiVieneVacio(this.txt_numeroContacto.getText(), "NUMERO CONTACTO");
            //this.comprobarSiVieneVacio(this.txt_correoContacto.getText(), "CORREO CONTACTO");

            //Rescatar datos
            String nombreEmpresa = this.txt_nombreEmpresa.getText();
            String giro = this.txt_giro.getText();
            String rutEmpresa = this.txt_rutEmpresa.getText().trim().replace(".", "").toUpperCase();

            String paginaWeb = this.txt_paginaWeb.getText();
            if (paginaWeb.isEmpty()) {
                paginaWeb = "";
            }

            String nombreContacto = this.txt_nombreContacto.getText();
            if (nombreContacto.isEmpty()) {
                nombreContacto = "";
            }

            String numeroContacto = this.txt_numeroContacto.getText();
            if (numeroContacto.isEmpty()) {
                nombreContacto = "";
            }

            String correoContacto = this.txt_correoContacto.getText();
            if (correoContacto.isEmpty()) {
                correoContacto = "";
            }

            String nombreBanco = this.txt_nombreBanco.getText();
            if (nombreBanco.isEmpty()) {
                nombreBanco = "";
            }
            
            String nroCuentaCorriente = this.txt_nroCuentaCorriente.getText();
            if (nroCuentaCorriente.isEmpty()) {
                nroCuentaCorriente = "";
            }
            

            /*Generar Proveedor*/
            ProveedorDao provedorDao = new ProveedorDao();
            //Agregar datos del menu OJO MAÑANA 
            if (provedorDao.insertarProveedor(nombreEmpresa, giro, rutEmpresa, paginaWeb, nombreContacto, numeroContacto, correoContacto,nombreBanco,nroCuentaCorriente)) {
                JOptionPane.showMessageDialog(null, "Proveedor Ingresado Correctamente");
                this.limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo ingresar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_nombreEmpresaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_nombreEmpresaCaretUpdate


    }//GEN-LAST:event_txt_nombreEmpresaCaretUpdate

    private void txt_rutEmpresaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_rutEmpresaCaretUpdate
        //Validar si existe rut en la bd   
        try {
            ProveedorDao provedorDao = new ProveedorDao();
            if (this.txt_rutEmpresa.getText().trim().length() == 0) {
                //No hacer metodo
            } else {
                //Buscar si existe carga datos, sino existe no hacer nada
                if (provedorDao.validarSiExisteProveedor(this.txt_rutEmpresa.getText())) {
                    Proveedor proveedor = new Proveedor();
                    proveedor = provedorDao.rescatarProveedorSegunRut(this.txt_rutEmpresa.getText().trim().toUpperCase());
                    this.txt_giro.setText(proveedor.getGiro());
                    this.txt_nombreEmpresa.setText(proveedor.getNombreEmpresa());
                    this.txt_paginaWeb.setText(proveedor.getPaginaWeb());
                    this.txt_nombreContacto.setText(proveedor.getNombreContacto());
                    this.txt_numeroContacto.setText(proveedor.getTelefono());
                    this.txt_correoContacto.setText(proveedor.getCorreo());
                    this.txt_nombreBanco.setText(proveedor.getNombreBanco());
                    this.txt_nroCuentaCorriente.setText(proveedor.getNroCuentaCorriente());
                } else {
                    System.out.println("No encontrado");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_txt_rutEmpresaCaretUpdate

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        try {
            this.comprobarSiVieneVacio(this.txt_nombreEmpresa.getText(), "NOMBRE EMPRESA");
            this.comprobarSiVieneVacio(this.txt_giro.getText(), "GIRO");
            this.comprobarSiVieneVacio(this.txt_rutEmpresa.getText(), "RUT EMPRESA");

            //Rescatar datos
            String nombreEmpresa = this.txt_nombreEmpresa.getText();
            String giro = this.txt_giro.getText();
            String rutEmpresa = this.txt_rutEmpresa.getText().trim().replace(".", "").toUpperCase();

            String paginaWeb = this.txt_paginaWeb.getText();
            if (paginaWeb.isEmpty()) {
                paginaWeb = "";
            }

            String nombreContacto = this.txt_nombreContacto.getText();
            if (nombreContacto.isEmpty()) {
                nombreContacto = "";
            }

            String numeroContacto = this.txt_numeroContacto.getText();
            if (numeroContacto.isEmpty()) {
                numeroContacto = "";
            }

            String correoContacto = this.txt_correoContacto.getText();
            if (correoContacto.isEmpty()) {
                correoContacto = "";
            }

             String nombreBanco = this.txt_nombreBanco.getText();
            if (nombreBanco.isEmpty()) {
                nombreBanco = "";
            }
            
            String nroCuentaCorriente = this.txt_nroCuentaCorriente.getText();
            if (nroCuentaCorriente.isEmpty()) {
                nroCuentaCorriente = "";
            }
            
            /*Generar Proveedor*/
            ProveedorDao provedorDao = new ProveedorDao();
            if (provedorDao.modificarProveedor(nombreEmpresa, giro, rutEmpresa, paginaWeb, nombreContacto, nombreContacto, correoContacto,nombreBanco,nroCuentaCorriente)) {
                JOptionPane.showMessageDialog(null, "Modificado Correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo Modificar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        try {
            this.comprobarSiVieneVacio(this.txt_rutEmpresa.getText(), "RUT EMPRESA");

            String rut = vista.proveedores.menuProveedores.txt_rutEmpresa.getText().replace(".", "").toUpperCase();

            ProveedorDao provedorDao = new ProveedorDao();
            int confirmacion = JOptionPane.YES_NO_OPTION;
            //System.out.println("Numero Confirmacion ELiminacion: "+ confirmacion);
            int numeroConfirmacion = JOptionPane.showConfirmDialog(null, "¿Desea Eliminarlo Realmente?", "Warning", confirmacion);

            if (numeroConfirmacion == 0) {
                if (provedorDao.eliminarProveedor(rut)) {
                    JOptionPane.showMessageDialog(null, "Eliminado Correctamente");
                    this.limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo Eliminar");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_consultaProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultaProveedoresActionPerformed
        menuConsultaRUTProveedor menu = new menuConsultaRUTProveedor();
        menu.setVisible(true);
    }//GEN-LAST:event_btn_consultaProveedoresActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuProveedores().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_consultaProveedores;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel txt_ayuda;
    private javax.swing.JTextField txt_correoContacto;
    private javax.swing.JTextField txt_giro;
    private javax.swing.JTextField txt_nombreBanco;
    private javax.swing.JTextField txt_nombreContacto;
    private javax.swing.JTextField txt_nombreEmpresa;
    private javax.swing.JTextField txt_nroCuentaCorriente;
    private javax.swing.JTextField txt_numeroContacto;
    private javax.swing.JTextField txt_paginaWeb;
    public static javax.swing.JTextField txt_rutEmpresa;
    // End of variables declaration//GEN-END:variables
}
