/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ordenTrabajo;

import control.OrdenTrabajoDao;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfredo
 */
public class menuOT extends javax.swing.JFrame {

    /**
     * Creates new form menuOT
     */
    public menuOT() {
        this.setTitle("Ventana Gestión Creación Orden de Trabajo");
        initComponents();
        this.generarFechaHoy();
        this.obtenerUltimoNroOT();
        this.txt_descripcion.setLineWrap(true);
    }

    public void obtenerUltimoNroOT() {
        if (this.txt_nroOrdenTrabajo.getText().equals("00000")) {
            OrdenTrabajoDao ordenx = new OrdenTrabajoDao();
            int nroOT = ordenx.obtenerUltimoNroOrdenTrabajo() + 1;
            this.txt_nroOrdenTrabajo.setText(String.valueOf(nroOT));
        }
    }

    public void generarFechaHoy() {
        Calendar today = Calendar.getInstance();
        Date fechaHoy = today.getTime();
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        String fechaStringBase = format.format(fechaHoy);
        //System.out.println("Fecha: " + fechaStringBase);
        this.txt_fechaCreacionHoy.setText(fechaStringBase);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_fechaCreacionHoy = new javax.swing.JLabel();
        btnAsignarFacturas = new javax.swing.JButton();
        txt_facturasAsignadas = new javax.swing.JTextField();
        txt_nombreResponsable = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnConsultarResponsable = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        btnConsultarCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_nroOrdenTrabajo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_fechaTermino = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        btnAgregarOT = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_OrdenCompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nombreOT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nro° OT: ");

        txt_fechaCreacionHoy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_fechaCreacionHoy.setText("00000");

        btnAsignarFacturas.setText("Asignar Facturas");
        btnAsignarFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarFacturasActionPerformed(evt);
            }
        });

        txt_facturasAsignadas.setText("S/A");
        txt_facturasAsignadas.setEnabled(false);

        txt_nombreResponsable.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cliente:");

        btnConsultarResponsable.setText("?");
        btnConsultarResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarResponsableActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Responsable:");

        txt_nombreCliente.setEnabled(false);

        btnConsultarCliente.setText("?");
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Creación:");

        txt_nroOrdenTrabajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_nroOrdenTrabajo.setText("00000");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha Termino:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Descripcion:");

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion);

        btnAgregarOT.setText("Agregar");
        btnAgregarOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarOTActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nro° OC:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nombre OT:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nroOrdenTrabajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fechaCreacionHoy)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_nombreOT))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                    .addComponent(txt_nombreResponsable)
                                    .addComponent(txt_nombreCliente))))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnConsultarResponsable)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnConsultarCliente)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnAgregarOT, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txt_facturasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAsignarFacturas))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_OrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_fechaCreacionHoy)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(txt_nroOrdenTrabajo)
                    .addComponent(txt_fechaTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCliente)
                    .addComponent(jLabel3)
                    .addComponent(btnAsignarFacturas)
                    .addComponent(txt_facturasAsignadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnConsultarResponsable)
                    .addComponent(txt_OrdenCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregarOT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        // TODO add your handling code here:
        vista.ordenTrabajo.menuConsultaCliente menu = new vista.ordenTrabajo.menuConsultaCliente();
        menu.setVisible(true);
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarResponsableActionPerformed
        // TODO add your handling code here:
        vista.ordenTrabajo.menuConsultaResponsable menu = new vista.ordenTrabajo.menuConsultaResponsable();
        menu.setVisible(true);
    }//GEN-LAST:event_btnConsultarResponsableActionPerformed

    private void btnAsignarFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarFacturasActionPerformed
        // TODO add your handling code here:
        vista.ordenTrabajo.menuFactura menu = new vista.ordenTrabajo.menuFactura();
        menu.setVisible(true);
    }//GEN-LAST:event_btnAsignarFacturasActionPerformed

    public void validarCamposVacios(String dato, String campo) throws Exception {
        if (dato.trim().isEmpty()) {
            throw new Exception("El campo " + campo + " no puede venir vacio");
        }
    }
    private void btnAgregarOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarOTActionPerformed
        try {
            /*Validar datos vacios*/
            this.validarCamposVacios(this.txt_nombreOT.getText(), "NOMBRE OT");
            this.validarCamposVacios(vista.ordenTrabajo.menuOT.txt_nombreCliente.getText(), "NOMBRE CLIENTE");
            this.validarCamposVacios(vista.ordenTrabajo.menuOT.txt_nombreResponsable.getText(), "NOMBRE RESPONSABLE");
            this.validarCamposVacios(this.txt_descripcion.getText(), "DESCRIPCION");

            if (vista.ordenTrabajo.menuOT.txt_facturasAsignadas.getText().equals("S/A")) {
                throw new Exception("Asigne un identificador de Factura");
            }

            int numeroOrdenCompra = 0;
            if (!this.txt_OrdenCompra.getText().isEmpty()) {
                numeroOrdenCompra = Integer.parseInt(this.txt_OrdenCompra.getText());
            }

            String fechaTermino = "";
            if (!this.txt_fechaTermino.getText().isEmpty()) {                
                fechaTermino = vista.ordenTrabajo.menuOT.txt_fechaTermino.getText();
            }

            String nombreResponsable = vista.ordenTrabajo.menuOT.txt_nombreResponsable.getText();
            String nombreCliente = vista.ordenTrabajo.menuOT.txt_nombreCliente.getText();

            //Rescatar el ID de la empresa
            OrdenTrabajoDao ordenTrabajox = new OrdenTrabajoDao();
            int idEmpresa = ordenTrabajox.obtenerIdEmpresa(nombreCliente.toUpperCase());
            System.out.println("ID EMPRESA: " + idEmpresa);

            int idFactura = Integer.parseInt(vista.ordenTrabajo.menuOT.txt_facturasAsignadas.getText());
            int nroOrden = Integer.parseInt(this.txt_nroOrdenTrabajo.getText());
            String fechaInicio = this.txt_fechaCreacionHoy.getText();
            String descripcion = this.txt_descripcion.getText();
            String nombreOT = this.txt_nombreOT.getText();
            System.out.println("FECHA : " + fechaInicio);

            if (!ordenTrabajox.validarSiExiste(nroOrden)) {
                //Crear
                if (ordenTrabajox.insertarOrdenTrabajo(nroOrden, idFactura, idEmpresa, nombreResponsable, fechaInicio, fechaTermino, descripcion, numeroOrdenCompra, nombreOT)) {
                    JOptionPane.showMessageDialog(null, "Se agrego Correctamente");
                    this.limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo Agregar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Esta Orden de Trabajo ya existe");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarOTActionPerformed

    public void limpiarCampos() {
        this.txt_nroOrdenTrabajo.setText("00000");
        this.obtenerUltimoNroOT();
        this.generarFechaHoy();
        this.txt_fechaTermino.setText("");
        this.txt_nombreOT.setText("");
        vista.ordenTrabajo.menuOT.txt_nombreCliente.setText("");
        vista.ordenTrabajo.menuOT.txt_nombreResponsable.setText("");
        vista.ordenTrabajo.menuOT.txt_facturasAsignadas.setText("S/A");
        this.txt_OrdenCompra.setText("");
        this.txt_descripcion.setText("");
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            OrdenTrabajoDao otx = new OrdenTrabajoDao();
            //validar si existe
            int nroOrdenTrabajo = Integer.parseInt(vista.ordenTrabajo.menuOT.txt_nroOrdenTrabajo.getText());
            if (otx.validarSiExiste(nroOrdenTrabajo)) {
                //rescatar datos
                this.validarCamposVacios(vista.ordenTrabajo.menuOT.txt_nombreOT.getText(), "NOMBRE ORDEN TRABAJO");

                String nombreOT = vista.ordenTrabajo.menuOT.txt_nombreOT.getText();

                String nombreEmpresa = vista.ordenTrabajo.menuOT.txt_nombreCliente.getText();
                int idEmpresa = otx.obtenerIdEmpresa(nombreEmpresa.toUpperCase());

                String nombreResponsable = vista.ordenTrabajo.menuOT.txt_nombreResponsable.getText();

                int numeroOC = 0;
                if (!vista.ordenTrabajo.menuOT.txt_OrdenCompra.getText().isEmpty()) {
                    numeroOC = Integer.parseInt(vista.ordenTrabajo.menuOT.txt_OrdenCompra.getText());
                }

                String descripcion = "";
                if (!vista.ordenTrabajo.menuOT.txt_descripcion.getText().isEmpty()) {
                    descripcion = vista.ordenTrabajo.menuOT.txt_descripcion.getText();
                }

                String fechaTermino = "";
                if (!vista.ordenTrabajo.menuOT.txt_fechaTermino.getText().isEmpty()) {
                    fechaTermino = vista.ordenTrabajo.menuOT.txt_fechaTermino.getText();
                }

                //Modificar
                if (otx.modificarOrdenTrabajo(nroOrdenTrabajo, idEmpresa, nombreResponsable, fechaTermino, descripcion, numeroOC, nombreOT)) {
                    JOptionPane.showMessageDialog(null, "Modificado Correctamente");
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo modificar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El número de OT no existe");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            //
            OrdenTrabajoDao otx = new OrdenTrabajoDao();
            int nroOrdenTrabajo = Integer.parseInt(vista.ordenTrabajo.menuOT.txt_nroOrdenTrabajo.getText());
            if (otx.validarSiExiste(nroOrdenTrabajo)) {
                //Existe asi que elimino
                int confirmacion = JOptionPane.YES_NO_OPTION;
                int numeroConfirmacion = JOptionPane.showConfirmDialog(null, "¿Desea Eliminarlo Realmente?", "Warning", confirmacion);
                if (numeroConfirmacion == 0) {
                    //Metodo eliminar
                    if (otx.eliminarOrdenTrabajo(nroOrdenTrabajo)) {
                        JOptionPane.showMessageDialog(null, "Eliminado Corretamente");
                        this.limpiarCampos();
                    }else{
                        JOptionPane.showMessageDialog(null, "No se ha podido eliminar");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe la orden de trabajo con ese ID");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuOT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuOT().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarOT;
    private javax.swing.JButton btnAsignarFacturas;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarResponsable;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txt_OrdenCompra;
    public static javax.swing.JTextArea txt_descripcion;
    public static javax.swing.JTextField txt_facturasAsignadas;
    public static javax.swing.JLabel txt_fechaCreacionHoy;
    public static javax.swing.JTextField txt_fechaTermino;
    public static javax.swing.JTextField txt_nombreCliente;
    public static javax.swing.JTextField txt_nombreOT;
    public static javax.swing.JTextField txt_nombreResponsable;
    public static javax.swing.JLabel txt_nroOrdenTrabajo;
    // End of variables declaration//GEN-END:variables
}
