/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ordenTrabajo;

import clase.Factura;
import control.FacturaDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfredo
 */
public class menuFactura extends javax.swing.JFrame {

    /**
     * Creates new form menuFactura
     */
    public menuFactura() {
        this.setTitle("Ventana Gestión Facturas");
        initComponents();
        this.cargarUltimoIDFactura();
        this.cargarDatosFacturaAsignada();
    }

    public void cargarUltimoIDFactura() {
        if (vista.ordenTrabajo.menuOT.txt_facturasAsignadas.getText().equals("S/A")) {
            //No asignada por lo tanto es una nueva OT
            FacturaDao facturax = new FacturaDao();
            int idFactura = facturax.obtenerUltimoIDFactura() + 1;
            this.txt_idFactura.setText(String.valueOf(idFactura));
        } else {
            this.txt_idFactura.setText(vista.ordenTrabajo.menuOT.txt_facturasAsignadas.getText());
        }
    }
    
    public void cargarDatosFacturaAsignada(){
         FacturaDao facturax = new FacturaDao();
            int idFactura = Integer.parseInt(this.txt_idFactura.getText());
            if (facturax.validarExistaFactura(idFactura)) {
                //Rescatar datos
                Factura factura = facturax.obtenerFacturaPorID(idFactura);
                System.out.println(factura.toString());
                this.txt_factura1.setText(String.valueOf(factura.getFactura1()));
                this.txt_factura2.setText(String.valueOf(factura.getFactura2()));
                this.txt_factura3.setText(String.valueOf(factura.getFactura3()));
                this.txt_factura4.setText(String.valueOf(factura.getFactura4()));
                this.txt_factura5.setText(String.valueOf(factura.getFactura5()));                
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_idFactura = new javax.swing.JLabel();
        txt_factura1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_factura2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_factura3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_factura4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_factura5 = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnAgregarYCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Id Factura:");

        txt_idFactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idFactura.setText("0000");

        jLabel3.setText("FACTURA 1:");

        jLabel4.setText("FACTURA 2:");

        txt_factura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_factura2ActionPerformed(evt);
            }
        });

        jLabel5.setText("FACTURA 3:");

        txt_factura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_factura3ActionPerformed(evt);
            }
        });

        jLabel6.setText("FACTURA 4:");

        jLabel7.setText("FACTURA 5:");

        btnAgregar.setText("AGREGAR CON DATOS");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnAgregarYCerrar.setText("AGREGAR Y CERRAR");
        btnAgregarYCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarYCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(34, 34, 34)
                                .addComponent(txt_factura1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(34, 34, 34)
                                .addComponent(txt_factura2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(34, 34, 34)
                                .addComponent(txt_factura3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(34, 34, 34)
                                .addComponent(txt_factura4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_idFactura))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_factura5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAgregarYCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_idFactura))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_factura1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_factura2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_factura3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_factura4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_factura5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarYCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_factura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_factura2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_factura2ActionPerformed

    private void txt_factura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_factura3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_factura3ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            //Validar que no exista y agregar   
            FacturaDao facturax = new FacturaDao();
            int idFactura = Integer.parseInt(this.txt_idFactura.getText());
            if (facturax.validarExistaFactura(idFactura)) {
                //Rescatar datos
                Factura factura = facturax.obtenerFacturaPorID(idFactura);
                this.txt_factura1.setText(String.valueOf(factura.getFactura1()));
                this.txt_factura2.setText(String.valueOf(factura.getFactura2()));
                this.txt_factura3.setText(String.valueOf(factura.getFactura3()));
                this.txt_factura4.setText(String.valueOf(factura.getFactura4()));
                this.txt_factura5.setText(String.valueOf(factura.getFactura5()));
                JOptionPane.showMessageDialog(null, "Datos cargados, ya existe este ID");
            } else {
                //Agregar nuevo
                if (this.txt_factura1.getText().isEmpty()) {
                    throw new Exception("Ingrese al menos una factura, sino utilizar opcion agregar y cerrar.");
                }
                int factura1 = Integer.parseInt(this.txt_factura1.getText());

                int factura2 = 0;
                if (!this.txt_factura2.getText().isEmpty()) {
                    factura2 = Integer.parseInt(this.txt_factura2.getText());
                }

                int factura3 = 0;
                if (!this.txt_factura3.getText().isEmpty()) {
                    factura3 = Integer.parseInt(this.txt_factura3.getText());
                }

                int factura4 = 0;
                if (!this.txt_factura4.getText().isEmpty()) {
                    factura4 = Integer.parseInt(this.txt_factura4.getText());
                }

                int factura5 = 0;
                if (!this.txt_factura2.getText().isEmpty()) {
                    factura5 = Integer.parseInt(this.txt_factura2.getText());
                }

                if (facturax.insertarFactura(factura1, factura2, factura3, factura4, factura5)) {
                    JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                    this.dispose();
                    vista.ordenTrabajo.menuOT.txt_facturasAsignadas.setText(this.txt_idFactura.getText());
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAgregarYCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarYCerrarActionPerformed
        try {
            int confirmacion = JOptionPane.YES_NO_OPTION;
            //System.out.println("Numero Confirmacion ELiminacion: "+ confirmacion);
            int numeroConfirmacion = JOptionPane.showConfirmDialog(null, "¿Desea Cerrar esta ventana?", "Warning", confirmacion);
            if (numeroConfirmacion == 0) {
                this.dispose();
            } else {
                //Validar que no exista y agregar   
                FacturaDao facturax = new FacturaDao();
                int idFactura = Integer.parseInt(this.txt_idFactura.getText());
                if (facturax.validarExistaFactura(idFactura)) {
                    //Rescatar datos
                    Factura factura = facturax.obtenerFacturaPorID(idFactura);
                    this.txt_factura1.setText(String.valueOf(factura.getFactura1()));
                    this.txt_factura2.setText(String.valueOf(factura.getFactura2()));
                    this.txt_factura3.setText(String.valueOf(factura.getFactura3()));
                    this.txt_factura4.setText(String.valueOf(factura.getFactura4()));
                    this.txt_factura5.setText(String.valueOf(factura.getFactura5()));
                    JOptionPane.showMessageDialog(null, "Datos cargados, ya existe este ID");
                } else {
                    //Agregar nuevo             
                    if (facturax.insertarFactura(0, 0, 0, 0, 0)) {
                        JOptionPane.showMessageDialog(null, "Agregado Correctamente");                        
                        vista.ordenTrabajo.menuOT.txt_facturasAsignadas.setText(this.txt_idFactura.getText());

                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo agregar");
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_btnAgregarYCerrarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            //Validar si existe, si existe modifico
            FacturaDao facturax = new FacturaDao();
            int idFactura = Integer.parseInt(this.txt_idFactura.getText());
            if (facturax.validarExistaFactura(idFactura)) {
                //modificar datos
                if (this.txt_factura1.getText().isEmpty()) {
                    throw new Exception("Ingrese al menos una factura, sino utilizar opcion agregar y cerrar.");
                }
                int factura1 = Integer.parseInt(this.txt_factura1.getText());

                int factura2 = 0;
                if (!this.txt_factura2.getText().isEmpty()) {
                    factura2 = Integer.parseInt(this.txt_factura2.getText());
                }

                int factura3 = 0;
                if (!this.txt_factura3.getText().isEmpty()) {
                    factura3 = Integer.parseInt(this.txt_factura3.getText());
                }

                int factura4 = 0;
                if (!this.txt_factura4.getText().isEmpty()) {
                    factura4 = Integer.parseInt(this.txt_factura4.getText());
                }

                int factura5 = 0;
                if (!this.txt_factura2.getText().isEmpty()) {
                    factura5 = Integer.parseInt(this.txt_factura2.getText());
                }
                
                if (facturax.modificarFactura(factura1, factura2, factura3, factura4, factura5, idFactura)) {
                    JOptionPane.showMessageDialog(null, "Modificado Correctamente");
                }else{
                    JOptionPane.showMessageDialog(null, "No se pudo modificar");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuFactura().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarYCerrar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_factura1;
    private javax.swing.JTextField txt_factura2;
    private javax.swing.JTextField txt_factura3;
    private javax.swing.JTextField txt_factura4;
    private javax.swing.JTextField txt_factura5;
    private javax.swing.JLabel txt_idFactura;
    // End of variables declaration//GEN-END:variables
}
