/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.cotizacion;

import clase.Cotizacion;
import clase.ListadoCotizacion;
import clase.ListadoExportarCotizacion;
import clase.ListadoPedido;
import control.CotizacionDao;
import control.ListadoPedidoDao;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author Alfredo
 */
public class menuListarCotizacion extends javax.swing.JFrame {

    /**
     * Creates new form menuListarCotizacion
     */
    public menuListarCotizacion() {
        this.setTitle("Ventana Buscar Cotizacion");
        initComponents();
        this.eliminarContenidoTabla();
        this.cargarTablaInicio();
    }

    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) this.tablaCotizacion.getModel();
        int a = this.tablaCotizacion.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void cargarTablaInicio() {
        try {
            CotizacionDao cotix = new CotizacionDao();

            DefaultTableModel modelo = (DefaultTableModel) this.tablaCotizacion.getModel();
            ArrayList<Cotizacion> listado = cotix.listadoCotizaciones();

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdCotizacion();
                fila[1] = listado.get(i).getNumeroOT();
                fila[2] = listado.get(i).getNombreEmpresa();
                fila[3] = listado.get(i).getFechaCreacion();
                fila[4] = listado.get(i).getTotal();
                fila[5] = listado.get(i).getEstadoCotizacion();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    public void cargarTablaInicioPorNombre(String nombreCliente) {
        try {
            CotizacionDao cotix = new CotizacionDao();

            DefaultTableModel modelo = (DefaultTableModel) this.tablaCotizacion.getModel();
            ArrayList<Cotizacion> listado = cotix.listadoCotizacionesPorNombreCliente(nombreCliente);

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdCotizacion();
                fila[1] = listado.get(i).getNumeroOT();
                fila[2] = listado.get(i).getNombreEmpresa();
                fila[3] = listado.get(i).getFechaCreacion();
                fila[4] = listado.get(i).getTotal();
                fila[5] = listado.get(i).getEstadoCotizacion();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        btnBuscarnombre = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btn_Exportar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCotizacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre Cliente: ");

        btnBuscarnombre.setText("BUSCAR");
        btnBuscarnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarnombreActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btn_Exportar.setText("EXPORTAR");
        btn_Exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(btn_Exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarnombre))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(btn_Exportar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buscar Cotizaciones por Nombre Cliente", jPanel1);

        tablaCotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NRO OT", "CLIENTE", "FECHA CREACION", "TOTAL", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCotizacion.getTableHeader().setReorderingAllowed(false);
        tablaCotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCotizacionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCotizacion);
        if (tablaCotizacion.getColumnModel().getColumnCount() > 0) {
            tablaCotizacion.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaCotizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCotizacionMouseClicked
        if (evt.getClickCount() == 2) {
            vista.cotizacion.menuCotizacion menu = new vista.cotizacion.menuCotizacion();
            menu.setVisible(true);
            //Rescatar datos y enviar
            CotizacionDao cotix = new CotizacionDao();
            int idCotizacion = Integer.parseInt(this.tablaCotizacion.getValueAt(this.tablaCotizacion.getSelectedRow(), 0).toString());
            Cotizacion coti = cotix.obtenerCotizaciones(idCotizacion);
            //Enviar valores
            vista.cotizacion.menuCotizacion.txt_idCotizacion.setText(String.valueOf(idCotizacion));
            vista.cotizacion.menuCotizacion.txt_fechaCreacion.setText(coti.getFechaCreacion());
            vista.cotizacion.menuCotizacion.txt_nroOT.setText(String.valueOf(coti.getNumeroOT()));
            vista.cotizacion.menuCotizacion.cboEstadoCotizacion.setSelectedItem(coti.getEstadoCotizacion());

        }
    }//GEN-LAST:event_tablaCotizacionMouseClicked

    private void btn_ExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExportarActionPerformed
        try {
            if (this.tablaCotizacion.getSelectedRowCount() < 0) {
                throw new Exception("Seleccione una fila para utilizar esta funcion");
            }

            String nombreUsuario = System.getProperty("user.name");
            String fechaCreación = this.tablaCotizacion.getValueAt(this.tablaCotizacion.getSelectedRow(), 3).toString();
            String nuevaCarpeta = "FECHA-" + fechaCreación;
            //Crear directorio y comprobar si existe
            File file = new File("C:/Users/" + nombreUsuario + "/Desktop/COTIZACION/" + nuevaCarpeta);
            if (!file.exists()) {
                if (file.mkdir()) {
                    System.out.println("Directory is created!");
                }
            }

            InputStream ExcelFileToRead = new FileInputStream("C:/FORMATOS/FORMATOCOTIZACION.xls");
            // OPCPackage pkg = OPCPackage.open(new File("C:/Users/Alfredo/Desktop/PEDIDOS/FORMATO.xlsx"));
            HSSFWorkbook wb = new HSSFWorkbook(ExcelFileToRead);
            //XSSFWorkbook wb = new XSSFWorkbook(pkg);
            String nombreHoja = wb.getSheetName(0);
            //HSSFSheet hoja = wb.getSheet(nombreHoja);
            HSSFSheet hoja = wb.getSheetAt(0);
            System.out.println("HOJA EXCEL: " + hoja);
            CotizacionDao cotix = new CotizacionDao();
            int idCotizacion = Integer.parseInt(this.tablaCotizacion.getValueAt(this.tablaCotizacion.getSelectedRow(), 0).toString());
            int numeroOT = Integer.parseInt(this.tablaCotizacion.getValueAt(this.tablaCotizacion.getSelectedRow(), 1).toString());
            ListadoExportarCotizacion cotiza = cotix.retornarDatosCotizacionExportar(idCotizacion, numeroOT);

            HSSFRow row = hoja.createRow(0);
            HSSFCell cell = row.createCell(1);
            //Nombre empresa
            cell.setCellValue(cotiza.getNombreEmpresa());
            //Nombre OT
            row = hoja.createRow(1);
            cell = row.createCell(1);
            cell.setCellValue(cotiza.getNombreOT());
            //ID Cotizacion
            row = hoja.createRow(2);
            cell = row.createCell(1);
            cell.setCellValue(cotiza.getIdCotizacion());
            //Total Cotizacion
            row = hoja.createRow(3);
            cell = row.createCell(1);
            cell.setCellValue(cotiza.getTotal());

            //Recorrer listado
            //Empiezo desde la fila de 16 y recorro 4 columnas
            ArrayList<ListadoCotizacion> listadoRecorrer = cotix.listadoCotizacion(idCotizacion);
            int filaInicial = 6;
            int columnaRecorre = 0;
            /*Seleccionar fila inicial*/
            for (int i = 0; i < listadoRecorrer.size(); i++) {
                row = hoja.createRow(filaInicial++);
                for (int j = 0; j <= 3; j++) {
                    cell = row.createCell(j);
                    if (j == 0) {
                        //Primera columna
                        cell.setCellValue(listadoRecorrer.get(i).getDescripcion());
                    } else if (j == 1) {
                        cell.setCellValue(listadoRecorrer.get(i).getCantidad());
                    } else if (j == 2) {
                        cell.setCellValue(listadoRecorrer.get(i).getPrecioUnitario());
                    } else if (j == 3) {
                        cell.setCellValue(listadoRecorrer.get(i).getSubTotal());
                    }
                }
            }

            String rutaNueva = "C:/Users/" + nombreUsuario + "/Desktop/COTIZACION/" + nuevaCarpeta + "/ID Cotiza -" + idCotizacion + ".xls";
            FileOutputStream fileOut = new FileOutputStream(rutaNueva);
            wb.write(fileOut);
            fileOut.flush();
            fileOut.close();
            JOptionPane.showMessageDialog(null, "Exportado correctamente \n" + rutaNueva);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_ExportarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        this.eliminarContenidoTabla();
        this.cargarTablaInicio();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarnombreActionPerformed
        try {
            if (this.txt_nombreCliente.getText().isEmpty()) {
                throw new Exception("Para utilizar esta funcion, debe ingresar al menos una funcion");
            }
            String nombreBuscar = this.txt_nombreCliente.getText();
            this.eliminarContenidoTabla();
            this.cargarTablaInicioPorNombre(nombreBuscar.toUpperCase());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnBuscarnombreActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuListarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuListarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuListarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuListarCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuListarCotizacion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarnombre;
    private javax.swing.JButton btn_Exportar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaCotizacion;
    private javax.swing.JTextField txt_nombreCliente;
    // End of variables declaration//GEN-END:variables
}
