/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.usuarios;

import clase.Persona;
import control.UsuarioDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo
 */
public class menuConsultarPersonaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form menuConsultarPersonaUsuario
     */
    public menuConsultarPersonaUsuario() {
        this.setTitle("Ventana consulta Persona");
        initComponents();
        this.cargarTablaInicio();
    }

    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) this.tablaPersonasUsuarios.getModel();
        int a = this.tablaPersonasUsuarios.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void cargarTablaInicio() {
        try {
            UsuarioDao usuariox = new UsuarioDao();
            DefaultTableModel modelo = (DefaultTableModel) this.tablaPersonasUsuarios.getModel();
            ArrayList<Persona> listaProveedores = usuariox.cargarNombreNroTrabajador();

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listaProveedores.size(); i++) {
                fila[0] = listaProveedores.get(i).getNombre();
                fila[1] = listaProveedores.get(i).getNroTrabajador();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    public void cargarTablaInicio(String nombre) {
        try {
            UsuarioDao usuariox = new UsuarioDao();
            DefaultTableModel modelo = (DefaultTableModel) this.tablaPersonasUsuarios.getModel();
            ArrayList<Persona> listaProveedores = usuariox.cargarNombreNroTrabajador(nombre);

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listaProveedores.size(); i++) {
                fila[0] = listaProveedores.get(i).getNombre();
                fila[1] = listaProveedores.get(i).getNroTrabajador();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_nombreBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonasUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnRecargar.setText("Recargar");
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre Buscar:");

        txt_nombreBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_nombreBuscarCaretUpdate(evt);
            }
        });

        tablaPersonasUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Nro Trabajador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPersonasUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaPersonasUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPersonasUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPersonasUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombreBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRecargar)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecargar)
                    .addComponent(jLabel1)
                    .addComponent(txt_nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        this.eliminarContenidoTabla();
        this.cargarTablaInicio();
        this.txt_nombreBuscar.setText("");
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void txt_nombreBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_nombreBuscarCaretUpdate
        try {
            String nombreBuscar;
            if (!this.txt_nombreBuscar.getText().trim().isEmpty()) {
                nombreBuscar = this.txt_nombreBuscar.getText().trim().toUpperCase();
                this.eliminarContenidoTabla();
                this.cargarTablaInicio(nombreBuscar);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_txt_nombreBuscarCaretUpdate

    private void tablaPersonasUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPersonasUsuariosMouseClicked
        if (evt.getClickCount() == 2) {
            String nombre = this.tablaPersonasUsuarios.getValueAt(this.tablaPersonasUsuarios.getSelectedRow(), 0).toString();
            String numero = this.tablaPersonasUsuarios.getValueAt(this.tablaPersonasUsuarios.getSelectedRow(), 1).toString();
            vista.usuarios.menuUsuarios.txtNombreUsuario.setText(nombre);
            vista.usuarios.menuUsuarios.txt_nroUsuario.setText(numero);
            this.dispose();
        }
    }//GEN-LAST:event_tablaPersonasUsuariosMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuConsultarPersonaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuConsultarPersonaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuConsultarPersonaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuConsultarPersonaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuConsultarPersonaUsuario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPersonasUsuarios;
    private javax.swing.JTextField txt_nombreBuscar;
    // End of variables declaration//GEN-END:variables
}
