/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.usuarios;

import clase.Usuario;
import control.UsuarioDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo
 */
public class menuUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form menuUsuarios
     */
    public menuUsuarios() {
        this.setTitle("Ventana Gestión Usuarios");
        initComponents();
        this.panelDatos.setVisible(false);
        this.txt_textoValida.setVisible(false);
        this.obtenerUltimoIDUsuario();
        
    }
    
    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) this.tablaUsuarios.getModel();
        int a = this.tablaUsuarios.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }
    
    public void cargarTablaInicio() {
        try {
            UsuarioDao usuariox = new UsuarioDao();
            DefaultTableModel modelo = (DefaultTableModel) this.tablaUsuarios.getModel();
            ArrayList<Usuario> listadoUsuario = usuariox.cargarListaUsuarios();
            
            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listadoUsuario.size(); i++) {
                fila[0] = listadoUsuario.get(i).getIdUsuario();
                fila[1] = listadoUsuario.get(i).getNroTrabajador();
                fila[2] = listadoUsuario.get(i).getClave();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }
    
    public void obtenerUltimoIDUsuario() {
        UsuarioDao usuariox = new UsuarioDao();
        int idUsuario = usuariox.obtenerUltimoIDUsuario() + 1;
        this.txt_idUsuario.setText(String.valueOf(idUsuario));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txt_nroUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_idUsuario = new javax.swing.JLabel();
        btnCrearPerfil = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_clave = new javax.swing.JPasswordField();
        txt_claveValida = new javax.swing.JPasswordField();
        txt_textoValida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        txt_claveListado = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        btnListadoUsuarios = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos USUARIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        panelDatos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre Usuario:");

        txtNombreUsuario.setEnabled(false);

        btnConsultar.setText("?");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Numero Usuario");

        txt_nroUsuario.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Clave:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID Usuario:");

        txt_idUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idUsuario.setText("0");

        btnCrearPerfil.setText("CREAR PERFIL");
        btnCrearPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPerfilActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jButton5.setText("Eliminar");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Validar Clave:");

        txt_claveValida.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_claveValidaCaretUpdate(evt);
            }
        });

        txt_textoValida.setText("jLabel7");

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nro Usuario", "Clave"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaUsuarios.getTableHeader().setReorderingAllowed(false);
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        jLabel2.setText("Clave");

        btnListadoUsuarios.setText("Listar");
        btnListadoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoUsuariosActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCrearPerfil)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(35, 35, 35)
                        .addComponent(jButton5)
                        .addGap(28, 28, 28)
                        .addComponent(btnLimpiar))
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_claveListado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnListadoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(txt_idUsuario))
                                                    .addGroup(panelDatosLayout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(panelDatosLayout.createSequentialGroup()
                                                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                                            .addComponent(jLabel4)
                                                            .addGap(18, 18, 18))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatosLayout.createSequentialGroup()
                                                            .addComponent(jLabel5)
                                                            .addGap(78, 78, 78)))
                                                    .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txt_nroUsuario)
                                                        .addComponent(txt_clave)
                                                        .addComponent(txt_claveValida, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))))
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnConsultar)
                                            .addComponent(txt_textoValida))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_idUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_nroUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_claveValida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_textoValida))
                .addGap(22, 22, 22)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_claveListado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnListadoUsuarios)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        System.out.println("CODIGO: " + evt.getKeyCode());
        if (evt.isControlDown() && evt.isAltDown() && evt.getKeyCode() == 0) {
            if (this.panelDatos.isVisible()) {
                this.panelDatos.setVisible(false);
            } else {
                this.panelDatos.setVisible(true);
            }
        }

    }//GEN-LAST:event_formKeyPressed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        vista.usuarios.menuConsultarPersonaUsuario menu = new vista.usuarios.menuConsultarPersonaUsuario();
        menu.setVisible(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txt_claveValidaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_claveValidaCaretUpdate
        try {
            if (!this.txt_claveValida.getText().equals(this.txt_clave.getText())) {
                this.txt_textoValida.setVisible(true);
                this.txt_textoValida.setText("Las claves no coinciden");
            } else {
                this.txt_textoValida.setVisible(false);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txt_claveValidaCaretUpdate

    private void btnListadoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoUsuariosActionPerformed
        try {
            if (this.txt_claveListado.getText().isEmpty()) {
                throw new Exception("Para usar esta funcion, ingrese la clave");
            } else {
                if (this.txt_claveListado.getText().trim().equals("misyr2011")) {
                    this.eliminarContenidoTabla();
                    this.cargarTablaInicio();
                } else {
                    this.txt_claveListado.setText("");
                    JOptionPane.showMessageDialog(null, "Contrseña incorrecta");
                }
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnListadoUsuariosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.eliminarContenidoTabla();
        this.txt_claveListado.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void limpiarCampos() {
        this.txt_clave.setText("");
        this.txt_claveValida.setText("");
        vista.usuarios.menuUsuarios.txtNombreUsuario.setText("");
        vista.usuarios.menuUsuarios.txt_nroUsuario.setText("");
        this.obtenerUltimoIDUsuario();
    }

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    public void validarCampoVacio(String dato, String campo) throws Exception {
        if (dato.trim().isEmpty()) {
            throw new Exception("El campo " + campo + " no puede venir vacio");
        }
    }
    private void btnCrearPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPerfilActionPerformed
        try {
            this.validarCampoVacio(vista.usuarios.menuUsuarios.txt_nroUsuario.getText(), "NUMERO TRABAJADOR");
            
            int nroTrabajador = Integer.parseInt(vista.usuarios.menuUsuarios.txt_nroUsuario.getText());
            String clave = "";
            if (this.txt_clave.getText().length() <= 0) {
                throw new Exception("Debe ingresar una clave");
            }
            this.validarCampoVacio(this.txt_claveValida.getText(), "VALIDAR CLAVE");
            
            if (this.txt_clave.getText().equals(this.txt_claveValida.getText())) {
                clave = this.txt_clave.getText();
                
                UsuarioDao usuariox = new UsuarioDao();
                
                if (!usuariox.validarSiExisteUsuarioTrabajador(nroTrabajador)) {
                    if (usuariox.insertarTipoTrabajo(nroTrabajador, clave)) {
                        JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                        this.limpiarCampos();
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo Agregar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Ya existe un usuario creado para este trabajador");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Las claves no coinciden");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCrearPerfilActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        try {
            if (evt.getClickCount() == 2) {
                UsuarioDao usuariox = new UsuarioDao();
                int nroTrabajador = Integer.parseInt(this.tablaUsuarios.getValueAt(this.tablaUsuarios.getSelectedRow(), 1).toString());
                int idUsuario = Integer.parseInt(this.tablaUsuarios.getValueAt(this.tablaUsuarios.getSelectedRow(), 0).toString());
                String clave = this.tablaUsuarios.getValueAt(this.tablaUsuarios.getSelectedRow(), 2).toString();
                String nombreUsuario = usuariox.obtenerNombreUsuario(nroTrabajador);
                
                this.txt_idUsuario.setText(String.valueOf(idUsuario));
                vista.usuarios.menuUsuarios.txtNombreUsuario.setText(nombreUsuario);
                vista.usuarios.menuUsuarios.txt_nroUsuario.setText(String.valueOf(nroTrabajador));
                this.txt_clave.setText(clave);
                this.txt_claveValida.setText(clave);
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            UsuarioDao usuariox = new UsuarioDao();
            int idUsuario = Integer.parseInt(this.txt_idUsuario.getText());
            if (usuariox.validarSiExisteIDUsuario(idUsuario)) {
                //Modificar
                int nroTrabajador = Integer.parseInt(vista.usuarios.menuUsuarios.txt_nroUsuario.getText());
                String clave = "";
                if (this.txt_clave.getText().length() <= 0) {
                    throw new Exception("Debe ingresar una clave");
                }
                this.validarCampoVacio(this.txt_claveValida.getText(), "VALIDAR CLAVE");
                
                if (this.txt_clave.getText().equals(this.txt_claveValida.getText())) {
                    clave = this.txt_clave.getText();
                    if (usuariox.modificarUsuario(nroTrabajador, clave, idUsuario)) {
                        JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                    } else {
                        JOptionPane.showMessageDialog(null, "No se pudo agregar");
                    }                    
                }else{
                    JOptionPane.showMessageDialog(null, "Claves no coinciden");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe este ID usuario");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuUsuarios().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnCrearPerfil;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListadoUsuarios;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JTable tablaUsuarios;
    public static javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JPasswordField txt_claveListado;
    private javax.swing.JPasswordField txt_claveValida;
    private javax.swing.JLabel txt_idUsuario;
    public static javax.swing.JTextField txt_nroUsuario;
    private javax.swing.JLabel txt_textoValida;
    // End of variables declaration//GEN-END:variables
}
