/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.pedidos;

import clase.ListadoPedido;
import control.ListadoPedidoDao;
import control.PedidoDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo
 */
public class modificarItemListadoPedido extends javax.swing.JFrame {

    /**
     * Creates new form modificarItemListadoPedido
     */
    public modificarItemListadoPedido() {
        this.setTitle("Ventana Modificar ITEM");
        initComponents();
        vista.pedidos.modificarItemListadoPedido.txt_idListado.setVisible(false);
    }

    
     public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) vista.pedidos.menuPedido.tablaListadoPedido.getModel();
        int a = vista.pedidos.menuPedido.tablaListadoPedido.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void cargarTablaInicio() {
        try {
            //Menu pedido
            ListadoPedidoDao listadoPedidox = new ListadoPedidoDao();

            DefaultTableModel modelo = (DefaultTableModel) vista.pedidos.menuPedido.tablaListadoPedido.getModel();
            int idPedido = Integer.parseInt(this.txt_idPedido.getText());
            ArrayList<ListadoPedido> listado = listadoPedidox.listadoITEMPedidosListaCompleta(idPedido);

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdListado();
                fila[1] = listado.get(i).getNombre();
                fila[2] = listado.get(i).getCantidad();
                fila[3] = listado.get(i).getPrecioUnitario();
                fila[4] = listado.get(i).getSubTotal();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    public void actualizarTotalCampoyBD(int idPedido) {
        PedidoDao pedidox = new PedidoDao();
        ListadoPedidoDao listadoPedidox = new ListadoPedidoDao();
        if (pedidox.validarSiExistePedido(idPedido)) {

            long subTotal = listadoPedidox.devolverTotalListaPedidos(idPedido);

            //Necesito actualizar la tabla y el texto con ese total
            if (pedidox.modificarSubTotal(subTotal, idPedido)) {
                JOptionPane.showMessageDialog(null, "Total Actualizado Correctamente");
                //Modificar Campo TOTAL
                vista.pedidos.menuPedido.txt_totalPedido.setText(this.cambiarFormatoMil(String.valueOf(subTotal)));
            }
            System.out.println("VALOR TOTAL: " + subTotal);
        }
    }
    
    
    public String cambiarFormatoMil(String valor) {
        String valorConSeparador = "";
        char[] arregloPaso = valor.toCharArray();
        int contadorPaso = 1;
        for (int i = arregloPaso.length - 1; i >= 0; i--) {
            if (contadorPaso == 3) {
                if (i == 0) {
                    valorConSeparador = valorConSeparador + arregloPaso[i];
                    contadorPaso = 1;
                } else {
                    valorConSeparador = valorConSeparador + arregloPaso[i] + ".";
                    contadorPaso = 1;
                }

            } else {
                valorConSeparador = valorConSeparador + arregloPaso[i];
                contadorPaso = contadorPaso + 1;
            }
            //System.out.println("LETRA: " + arregloPaso[i]);
        }

        StringBuilder stringPaso = new StringBuilder(valorConSeparador);
        valorConSeparador = stringPaso.reverse().toString();

        return valorConSeparador;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_idPedido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_codigoProducto = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_precioUnitario = new javax.swing.JTextField();
        txt_subTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        txt_idListado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_idPedido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idPedido.setText("00000");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID Pedido:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Codigo Producto:");

        txt_cantidad.setText("0");
        txt_cantidad.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cantidadCaretUpdate(evt);
            }
        });

        btnBuscarProducto.setText("?");
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Cantidad");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Precio Unitario");

        txt_precioUnitario.setText("0");
        txt_precioUnitario.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_precioUnitarioCaretUpdate(evt);
            }
        });

        txt_subTotal.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total");

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        txt_idListado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_idListado.setText("00000");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txt_idPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_idListado))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_codigoProducto)
                                        .addComponent(txt_precioUnitario)
                                        .addComponent(txt_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                        .addComponent(txt_subTotal)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarProducto)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_idPedido)
                            .addComponent(txt_idListado))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_precioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cantidadCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cantidadCaretUpdate
        try {
            int cantidad = 0;
            if (!this.txt_cantidad.getText().isEmpty()) {
                cantidad = Integer.parseInt(this.txt_cantidad.getText().replace(".", ""));
            }

            long precioUnitario = 0;
            if (!this.txt_precioUnitario.getText().isEmpty()) {
                precioUnitario = Long.parseLong(this.txt_precioUnitario.getText().replace(".", ""));
            }

            long subTotal = cantidad * precioUnitario;

            this.txt_subTotal.setText(this.cambiarFormatoMil(String.valueOf(subTotal)));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txt_cantidadCaretUpdate

    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
        vista.pedidos.menuConsultarProductosPedidoModif menu = new vista.pedidos.menuConsultarProductosPedidoModif();
        menu.setVisible(true);
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void txt_precioUnitarioCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_precioUnitarioCaretUpdate
        try {
            int cantidad = 0;
            if (!this.txt_cantidad.getText().isEmpty()) {
                cantidad = Integer.parseInt(this.txt_cantidad.getText().replace(".", ""));
            }

            long precioUnitario = 0;
            if (!this.txt_precioUnitario.getText().isEmpty()) {
                precioUnitario = Long.parseLong(this.txt_precioUnitario.getText().replace(".", ""));
            }

            long subTotal = cantidad * precioUnitario;

           this.txt_subTotal.setText(this.cambiarFormatoMil(String.valueOf(subTotal)));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_txt_precioUnitarioCaretUpdate

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            if (vista.pedidos.modificarItemListadoPedido.txt_codigoProducto.getText().isEmpty()) {
                throw new Exception("Ingrese el codigo del producto");
            }
            int cantidad = 0;
            if (!this.txt_cantidad.getText().isEmpty()) {
                cantidad = Integer.parseInt(this.txt_cantidad.getText().replace(".", ""));
            }

            long precioUnitario = 0;
            if (!this.txt_precioUnitario.getText().isEmpty()) {
                precioUnitario = Long.parseLong(this.txt_precioUnitario.getText().replace(".", ""));
            }

            long subTotal = 0;
            if (!this.txt_subTotal.getText().isEmpty()) {
                subTotal = Long.parseLong(this.txt_subTotal.getText().replace(".", ""));
            }

            int idProducto = Integer.parseInt(vista.pedidos.modificarItemListadoPedido.txt_codigoProducto.getText());

            int idPedido = Integer.parseInt(vista.pedidos.modificarItemListadoPedido.txt_idPedido.getText());
            int idListado = Integer.parseInt(vista.pedidos.modificarItemListadoPedido.txt_idListado.getText());

            //Metodo Agregar
            ListadoPedidoDao listadoPedidox = new ListadoPedidoDao();
            if (listadoPedidox.modificarItemPedido(precioUnitario, cantidad, subTotal, idProducto, idListado)) {
                JOptionPane.showMessageDialog(null, "Se agrego correctamente");
                this.eliminarContenidoTabla();
                this.cargarTablaInicio();
                this.actualizarTotalCampoyBD(idPedido);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "No se pudo agregar");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(modificarItemListadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(modificarItemListadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(modificarItemListadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(modificarItemListadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new modificarItemListadoPedido().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField txt_cantidad;
    public static javax.swing.JTextField txt_codigoProducto;
    public static javax.swing.JLabel txt_idListado;
    public static javax.swing.JLabel txt_idPedido;
    public static javax.swing.JTextField txt_precioUnitario;
    public static javax.swing.JTextField txt_subTotal;
    // End of variables declaration//GEN-END:variables
}
