/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.categoria;

import clase.Categoria;
import control.CategoriaDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo
 */
public class menuCategoria extends javax.swing.JFrame {

    /**
     * Creates new form menuCategoria
     */
    public menuCategoria() {
        this.setTitle("Ventana Categoria Productos");
        initComponents();
        this.rescatarIDCategoria();
        this.txt_descripccion.setLineWrap(true);
        this.cargarTablaInicio();
    }

    public void rescatarIDCategoria() {
        CategoriaDao categoriax = new CategoriaDao();
        int id = categoriax.obtenerIDCategoria() + 1;
        this.txt_numeroCategoria.setText(String.valueOf(id));
    }

    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) this.tablaCategoria.getModel();
        int a = this.tablaCategoria.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void cargarTablaInicio() {

        if (this.tablaCategoria.getSelectedRow() != 0) {
            this.eliminarContenidoTabla();
        }
        CategoriaDao categoriax = new CategoriaDao();
        ArrayList<Categoria> listado = categoriax.obtenerListadoCategoria();
        DefaultTableModel modelo = (DefaultTableModel) this.tablaCategoria.getModel();

        Object[] fila = new Object[modelo.getColumnCount()];
        for (int i = 0; i < listado.size(); i++) {
            fila[0] = listado.get(i).getId();
            fila[1] = listado.get(i).getNombreCategoria();
            fila[2] = listado.get(i).getDescripcion();

            modelo.addRow(fila);
        }
    }

    public void cargarTablaInicioPornombre(String nombreBuscar) {

        if (this.tablaCategoria.getSelectedRow() != 0) {
            this.eliminarContenidoTabla();
        }
        CategoriaDao categoriax = new CategoriaDao();
        ArrayList<Categoria> listado = categoriax.obtenerListadoCategoriaPorNombre(nombreBuscar);
        DefaultTableModel modelo = (DefaultTableModel) this.tablaCategoria.getModel();

        Object[] fila = new Object[modelo.getColumnCount()];
        for (int i = 0; i < listado.size(); i++) {
            fila[0] = listado.get(i).getId();
            fila[1] = listado.get(i).getNombreCategoria();
            fila[2] = listado.get(i).getDescripcion();

            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripccion = new javax.swing.JTextArea();
        txt_numeroCategoria = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_limpiarCeldas = new javax.swing.JButton();
        txt_nombreCategoria = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombreBuscar = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCategoria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("ID Categoría:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombre Categoria:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Descripcción:");

        txt_descripccion.setColumns(20);
        txt_descripccion.setRows(5);
        txt_descripccion.setTabSize(4);
        txt_descripccion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txt_descripccion);

        txt_numeroCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_numeroCategoria.setText("1");

        btn_agregar.setText("Agregar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_limpiarCeldas.setText("Limpiar Casillas");
        btn_limpiarCeldas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCeldasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btn_agregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_modificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_eliminar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btn_limpiarCeldas)))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_numeroCategoria))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_nombreCategoria))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_numeroCategoria))
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_modificar)
                    .addComponent(btn_eliminar))
                .addGap(18, 18, 18)
                .addComponent(btn_limpiarCeldas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Buscar Categoria:");

        txt_nombreBuscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_nombreBuscarCaretUpdate(evt);
            }
        });

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btn_actualizar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar)
                    .addComponent(jLabel4)
                    .addComponent(btn_actualizar))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        tablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCategoria.getTableHeader().setReorderingAllowed(false);
        tablaCategoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCategoriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaCategoria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void validarCamposVacio(String dato, String campo) throws Exception {
        if (dato.trim().length() == 0) {
            throw new Exception("El campo " + campo + " no puede venir vacio");
        }
    }

    public void limpiarCampos() {
        this.txt_nombreCategoria.setText("");
        this.txt_descripccion.setText("");
        this.txt_nombreBuscar.setText("");
        this.rescatarIDCategoria();
    }

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        /*Agregar Categoria*/
        try {
            this.validarCamposVacio(this.txt_nombreCategoria.getText(), "NOMBRE CATEGORIA");
            this.validarCamposVacio(this.txt_descripccion.getText(), "DESCRPCION");

            int idCategoria = Integer.parseInt(this.txt_numeroCategoria.getText());
            String nombreCategoria = this.txt_nombreCategoria.getText();
            String descripccion = this.txt_descripccion.getText();

            CategoriaDao categoriax = new CategoriaDao();
            /*Validar si existe en la bd*/
            if (!categoriax.validarSiExiste(idCategoria)) {
                //Agregar y llamar metodo insertar categoria
                if (categoriax.insertarCategoria(nombreCategoria, descripccion)) {
                    JOptionPane.showMessageDialog(null, "Se agrego Correctamente");
                    this.limpiarCampos();

                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo agregar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ya Existe esta categoria");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_limpiarCeldasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCeldasActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
    }//GEN-LAST:event_btn_limpiarCeldasActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        this.eliminarContenidoTabla();
        this.cargarTablaInicio();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void tablaCategoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCategoriaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            //Enviar datos a panel
            int idTipo = Integer.parseInt(this.tablaCategoria.getValueAt(this.tablaCategoria.getSelectedRow(), 0).toString());
            CategoriaDao categoriax = new CategoriaDao();
            Categoria categoria = categoriax.obtenerDatosCategoria(idTipo);

            this.txt_numeroCategoria.setText(String.valueOf(idTipo));
            this.txt_nombreCategoria.setText(categoria.getNombreCategoria());
            this.txt_descripccion.setText(categoria.getDescripcion());
        }
    }//GEN-LAST:event_tablaCategoriaMouseClicked

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        try {
            CategoriaDao categoriax = new CategoriaDao();
            int idTipo = Integer.parseInt(this.txt_numeroCategoria.getText());
            if (categoriax.validarSiExiste(idTipo)) {
                //Modifico -
                this.validarCamposVacio(this.txt_nombreCategoria.getText(), "NOMBRE CATEGORIA");
                this.validarCamposVacio(this.txt_descripccion.getText(), "DESCRIPCION");
                String nombreCategoria = this.txt_nombreCategoria.getText();
                String descripcion = this.txt_descripccion.getText();
                if (categoriax.modificarCategoria(idTipo, nombreCategoria, descripcion)) {
                    JOptionPane.showMessageDialog(null, "Se modifico Correctmente");
                } else {
                    JOptionPane.showMessageDialog(null, "No se pudo modificar");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Primero cree la     categoria");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }


    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        //validar si existe
        CategoriaDao categoriax = new CategoriaDao();
        int idtipoCategoria = Integer.parseInt(this.txt_numeroCategoria.getText());

        if (categoriax.validarSiExiste(idtipoCategoria)) {
            //Consultar si lo elimino
            int confirmacion = JOptionPane.YES_NO_OPTION;
            //System.out.println("Numero Confirmacion ELiminacion: "+ confirmacion);
            int numeroConfirmacion = JOptionPane.showConfirmDialog(null, "¿Desea Eliminarlo Realmente?", "Warning", confirmacion);

            if (numeroConfirmacion == 0) {
                //Eliminar
                if (categoriax.eliminarCategoria(idtipoCategoria)) {
                    JOptionPane.showMessageDialog(null, "Se elimino correctamente");
                    this.limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(null, "No existe ese ID");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "No existe ese ID de Categoria");
        }


    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try {
            this.validarCamposVacio(this.txt_nombreBuscar.getText(), "NOMBRE BUSCAR");
            String nombreBuscar = this.txt_nombreBuscar.getText().trim();
            this.cargarTablaInicioPornombre(nombreBuscar);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_nombreBuscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_nombreBuscarCaretUpdate
        // TODO add your handling code here:
        if (!this.txt_nombreBuscar.getText().isEmpty()) {
            String nombreBuscar = this.txt_nombreBuscar.getText();
            this.cargarTablaInicioPornombre(nombreBuscar);
        }
        
    }//GEN-LAST:event_txt_nombreBuscarCaretUpdate

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuCategoria().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiarCeldas;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaCategoria;
    private javax.swing.JTextArea txt_descripccion;
    private javax.swing.JTextField txt_nombreBuscar;
    private javax.swing.JTextField txt_nombreCategoria;
    private javax.swing.JLabel txt_numeroCategoria;
    // End of variables declaration//GEN-END:variables
}
