/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.trabajoRealizado;

import clase.ListadoTrabajosRealizados;
import clase.TrabajoRealizadoExportacion;
import clase.TrabajosRealizados;
import control.TrabajosRealizadosDao;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

/**
 *
 * @author Alfredo
 */
public class menuListarTrabajoRealizado extends javax.swing.JFrame {

    /**
     * Creates new form menuListarTrabajoRealizado
     */
    public menuListarTrabajoRealizado() {
        this.setTitle("Ventana Consultar Trabajos Realizados");
        initComponents();
        this.cargarTablaInicio();
    }

    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) this.tablaTrabajosRealizados.getModel();
        int a = this.tablaTrabajosRealizados.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void cargarTablaInicio() {
        try {
            TrabajosRealizadosDao trabajoRealizadox = new TrabajosRealizadosDao();
            DefaultTableModel modelo = (DefaultTableModel) this.tablaTrabajosRealizados.getModel();
            ArrayList<TrabajosRealizados> listado = trabajoRealizadox.listadoTrabajosRealizados();

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdTrabajosRealizados();
                fila[1] = listado.get(i).getNroOT();
                fila[2] = listado.get(i).getNombreOT();
                fila[3] = listado.get(i).getNombreEmpresa();
                fila[4] = listado.get(i).getSubTotal();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    public void cargarTablaInicio(int nroOT) {
        try {
            TrabajosRealizadosDao trabajoRealizadox = new TrabajosRealizadosDao();
            DefaultTableModel modelo = (DefaultTableModel) this.tablaTrabajosRealizados.getModel();
            ArrayList<TrabajosRealizados> listado = trabajoRealizadox.listadoTrabajosRealizados(nroOT);

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdTrabajosRealizados();
                fila[1] = listado.get(i).getNroOT();
                fila[2] = listado.get(i).getNombreOT();
                fila[3] = listado.get(i).getNombreEmpresa();
                fila[4] = listado.get(i).getSubTotal();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nroOT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnExportar = new javax.swing.JButton();
        btnBuscarNROOT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTrabajosRealizados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nro° Orden de Trabajo");

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnExportar.setText("EXPORTAR");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        btnBuscarNROOT.setText("?");
        btnBuscarNROOT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNROOTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_nroOT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarNROOT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(btnExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_nroOT)
                            .addComponent(jLabel1)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarNROOT))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Buscar por número Orden de Trabajo", jPanel1);

        tablaTrabajosRealizados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRO° OT", "NOMBRE OT", "CLIENTE", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTrabajosRealizados.getTableHeader().setReorderingAllowed(false);
        tablaTrabajosRealizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTrabajosRealizadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTrabajosRealizados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTrabajosRealizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTrabajosRealizadosMouseClicked
        try {
            if (evt.getClickCount() == 2) {
                int idTrabajoRealizado = Integer.parseInt(this.tablaTrabajosRealizados.getValueAt(this.tablaTrabajosRealizados.getSelectedRow(), 0).toString());
                int nroTrabajo = Integer.parseInt(this.tablaTrabajosRealizados.getValueAt(this.tablaTrabajosRealizados.getSelectedRow(), 1).toString());

                vista.trabajoRealizado.menuTrabajoRealizado menu = new vista.trabajoRealizado.menuTrabajoRealizado();
                menu.setVisible(true);

                vista.trabajoRealizado.menuTrabajoRealizado.txt_NroOT.setText(String.valueOf(nroTrabajo));
                vista.trabajoRealizado.menuTrabajoRealizado.txt_idTrabajoRealizado.setText(String.valueOf(idTrabajoRealizado));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tablaTrabajosRealizadosMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.eliminarContenidoTabla();
        this.cargarTablaInicio();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (this.txt_nroOT.getText().isEmpty()) {
                throw new Exception("Porfavor ingrese un Nro° de Orden de Trabajo");
            }

            int nroOT = Integer.parseInt(vista.trabajoRealizado.menuListarTrabajoRealizado.txt_nroOT.getText());
            this.eliminarContenidoTabla();
            this.cargarTablaInicio(nroOT);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarNROOTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNROOTActionPerformed
        vista.trabajoRealizado.menuConsultarOTTrabajosRealizadosListar menu = new vista.trabajoRealizado.menuConsultarOTTrabajosRealizadosListar();
        menu.setVisible(true);
    }//GEN-LAST:event_btnBuscarNROOTActionPerformed

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        try {
            if (this.tablaTrabajosRealizados.getSelectedRowCount() < 0) {
                throw new Exception("Seleccione una fila para utilizar esta funcion");
            }

            String nombreUsuario = System.getProperty("user.name");

            Calendar today = Calendar.getInstance();
            Date fechaHoy = today.getTime();
            SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
            String fechaStringBase = format.format(fechaHoy);

            String nuevaCarpeta = "FECHA-HOY-" + fechaStringBase;
            //Crear directorio y comprobar si existe
            File file = new File("C:/Users/" + nombreUsuario + "/Desktop/TRABAJOS/" + nuevaCarpeta);
            if (!file.exists()) {
                if (file.mkdir()) {
                    System.out.println("Directory is created!");
                }
            }

            InputStream ExcelFileToRead = new FileInputStream("C:/FORMATOS/FORMATOTRABAJOS.xls");
            // OPCPackage pkg = OPCPackage.open(new File("C:/Users/Alfredo/Desktop/PEDIDOS/FORMATO.xlsx"));
            HSSFWorkbook wb = new HSSFWorkbook(ExcelFileToRead);
            //XSSFWorkbook wb = new XSSFWorkbook(pkg);
            String nombreHoja = wb.getSheetName(0);
            //HSSFSheet hoja = wb.getSheet(nombreHoja);
            HSSFSheet hoja = wb.getSheetAt(0);
            System.out.println("HOJA EXCEL: " + hoja);

            int idTrabajoRealizado = Integer.parseInt(this.tablaTrabajosRealizados.getValueAt(this.tablaTrabajosRealizados.getSelectedRow(), 0).toString());
            int nroOT = Integer.parseInt(this.tablaTrabajosRealizados.getValueAt(this.tablaTrabajosRealizados.getSelectedRow(), 1).toString());

            TrabajosRealizadosDao trabajox = new TrabajosRealizadosDao();
            TrabajoRealizadoExportacion trabajito = trabajox.exportarObjetoTrabajoRealizado(nroOT);

            HSSFRow row = hoja.createRow(0);
            HSSFCell cell = row.createCell(1);
            //Nombre empresa
            cell.setCellValue(trabajito.getNombreCliente());
            //Nombre OT
            row = hoja.createRow(1);
            cell = row.createCell(1);
            cell.setCellValue(trabajito.getNombreOT());
            //Nombre Responsable
            row = hoja.createRow(2);
            cell = row.createCell(1);
            cell.setCellValue(trabajito.getResponsable());
            //Nro insumo
            row = hoja.createRow(3);
            cell = row.createCell(1);
            cell.setCellValue(trabajito.getFechaInicio());
            //TOTAL
            row = hoja.createRow(4);
            cell = row.createCell(1);
            cell.setCellValue(trabajito.getFechaTermino());
            //N° OT
            row = hoja.createRow(5);
            cell = row.createCell(1);
            cell.setCellValue(trabajito.getNroOT());

            //N° OT
            row = hoja.createRow(6);
            cell = row.createCell(1);
            cell.setCellValue(trabajito.getSubTotal());

            //Recorrer listado
            ArrayList<ListadoTrabajosRealizados> listadoRecorrer = trabajox.listadoITEMSTrabajosRealizadosExportar(idTrabajoRealizado);
            int filaInicial = 10;
            int columnaRecorre = 0;
            /*Seleccionar fila inicial*/
            for (int i = 0; i < listadoRecorrer.size(); i++) {
                row = hoja.createRow(filaInicial++);
                for (int j = 0; j <= 6; j++) {
                    cell = row.createCell(j);
                    if (j == 0) {
                        //Primera columna
                        cell.setCellValue(listadoRecorrer.get(i).getNombreTrabajo());
                    } else if (j == 1) {
                        cell.setCellValue(listadoRecorrer.get(i).getTipoTrabajo());
                    } else if (j == 2) {
                        cell.setCellValue(listadoRecorrer.get(i).getNombreDepto());
                    } else if (j == 3) {
                        cell.setCellValue(listadoRecorrer.get(i).getHorasTrabajadas());
                    } else if (j == 4) {
                        cell.setCellValue(listadoRecorrer.get(i).getValorHora());
                    } else if (j == 5) {
                        cell.setCellValue(listadoRecorrer.get(i).getSubTotal());
                    } else if (j == 6) {
                        cell.setCellValue(listadoRecorrer.get(i).getDescripcion());
                    }                    
                }
            }

            String rutaNueva = "C:/Users/" + nombreUsuario + "/Desktop/TRABAJOS/" + nuevaCarpeta + "/ID TRABAJO-REALIZADOS -" + idTrabajoRealizado + ".xls";
            FileOutputStream fileOut = new FileOutputStream(rutaNueva);
            wb.write(fileOut);
            fileOut.flush();
            fileOut.close();
            JOptionPane.showMessageDialog(null, "Exportado Correctamente\n" + rutaNueva);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnExportarActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuListarTrabajoRealizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuListarTrabajoRealizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuListarTrabajoRealizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuListarTrabajoRealizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuListarTrabajoRealizado().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarNROOT;
    private javax.swing.JButton btnExportar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaTrabajosRealizados;
    public static javax.swing.JTextField txt_nroOT;
    // End of variables declaration//GEN-END:variables
}
