/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.trabajoRealizado;

import clase.TipoTrabajo;
import control.DepartamentoDao;
import control.TipoTrabajoDao;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alfredo
 */
public class menuConsultaTipoTrabajoMoficar extends javax.swing.JFrame {

    boolean paso = false;

    /**
     * Creates new form menuConsultaTipoTrabajo
     */
    public menuConsultaTipoTrabajoMoficar() {
        this.setTitle("Ventana Consulta Tipo Trabajo");
        initComponents();
        this.llenarComboBoxGiroProveedores();
    }

    public void eliminarContenidoTabla() {
        DefaultTableModel tb = (DefaultTableModel) this.tablaTipoTrabajo.getModel();
        int a = this.tablaTipoTrabajo.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    public void llenarComboBoxGiroProveedores() {
        try {
            DepartamentoDao departamentox = new DepartamentoDao();
            ArrayList<String> listado = departamentox.rescatarNombresDeptoComboBox();

            this.cboDepartamento.removeAllItems();

            for (int i = -1; i < listado.size(); i++) {
                if (i == -1) {
                    this.cboDepartamento.addItem("Seleccionar");
                } else {
                    this.cboDepartamento.addItem(listado.get(i));
                }
            }
            /*Fin llenado*/
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema CBO: " + e.getMessage());
        }
    }

    public void cargarTablaInicio() {
        try {
            TipoTrabajoDao tipox = new TipoTrabajoDao();

            DefaultTableModel modelo = (DefaultTableModel) this.tablaTipoTrabajo.getModel();
            ArrayList<TipoTrabajo> listado = tipox.obtenerListadoTipoTrabajo();

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdTipoTrabajo();
                fila[1] = listado.get(i).getNombreDepto();
                fila[2] = listado.get(i).getTipoDepto();
                fila[3] = listado.get(i).getValorHora();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }

    
    public void cargarTablaInicio(String nombreDPTO) {
        try {
            TipoTrabajoDao tipox = new TipoTrabajoDao();

            DefaultTableModel modelo = (DefaultTableModel) this.tablaTipoTrabajo.getModel();
            ArrayList<TipoTrabajo> listado = tipox.obtenerListadoTipoTrabajo(nombreDPTO);

            Object[] fila = new Object[modelo.getColumnCount()];
            for (int i = 0; i < listado.size(); i++) {
                fila[0] = listado.get(i).getIdTipoTrabajo();
                fila[1] = listado.get(i).getNombreDepto();
                fila[2] = listado.get(i).getTipoDepto();
                fila[3] = listado.get(i).getValorHora();
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Problema Tabla Proveedores: " + e.getMessage());
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboDepartamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTipoTrabajo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Departamentos:");

        cboDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboDepartamentoItemStateChanged(evt);
            }
        });

        tablaTipoTrabajo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DPTO", "TIPO", "VALOR HORA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTipoTrabajo.getTableHeader().setReorderingAllowed(false);
        tablaTipoTrabajo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTipoTrabajoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTipoTrabajo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cboDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboDepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboDepartamentoItemStateChanged
        try {
            if (evt.getItem().equals("Seleccionar")) {
                if (this.tablaTipoTrabajo.getRowCount() >= 0) {
                    this.eliminarContenidoTabla();
                }
                this.cargarTablaInicio();
            } else {
                String nombreDpto = evt.getItem().toString();
                if (this.tablaTipoTrabajo.getRowCount() >= 0) {
                    this.eliminarContenidoTabla();
                }
                this.cargarTablaInicio(nombreDpto);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_cboDepartamentoItemStateChanged

    private void tablaTipoTrabajoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTipoTrabajoMouseClicked
        try{
            if (evt.getClickCount()==2) {
                int idTipoTrabajo = Integer.parseInt(this.tablaTipoTrabajo.getValueAt(this.tablaTipoTrabajo.getSelectedRow(), 0).toString());
                
                vista.trabajoRealizado.modificarITEMTrabajoRealizado.txt_tipoTrabajo.setText(String.valueOf(idTipoTrabajo));
                vista.trabajoRealizado.modificarITEMTrabajoRealizado.txt_horasTrabajadas.setText("0");
                this.dispose();
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_tablaTipoTrabajoMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(menuConsultaTipoTrabajoMoficar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(menuConsultaTipoTrabajoMoficar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(menuConsultaTipoTrabajoMoficar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(menuConsultaTipoTrabajoMoficar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new menuConsultaTipoTrabajoMoficar().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboDepartamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTipoTrabajo;
    // End of variables declaration//GEN-END:variables
}
